# Generated by Django 5.1.3 on 2024-11-26 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0001_initial'),
        ('produtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('quantidade_agua', models.FloatField(blank=True, null=True)),
                ('emissao_carbono', models.FloatField(blank=True, null=True)),
                ('quantidade_energia', models.FloatField(blank=True, null=True)),
                ('quantidade_residuos', models.FloatField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes', to='lote.lote')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_enviadas', to='produtor.produtor')),
            ],
        ),
    ]
